// src/views/phone/record/index.vue
<template>
    <div class="oilRecord">
        <div class="headFixed">
            <header>
                <i class="cubeic-back" @click="$router.push({name:'phoneHome'})"></i>
                兑换记录
            </header>
            <div class="whoSelectW">
                <p :class="typeFlag==0?'whoSelectLogo':''"  @click="directCharge()" v-show="!yingqiudiShow">
                    <span>直充</span>
                    <span></span>
                </p>
                <span class="divide" v-show="!yingqiudiShow">|</span>
                <p :class="typeFlag==1?'whoSelectLogo':''"   @click="cardCharge()">
                    <span >充值卡</span>
                    <span></span>
                </p>
            </div>
        </div>
        <div class="scroll-list-wrap">
            <cube-scroll ref="scroll" :data="recodeList" :options="options" @pulling-up="onPullingUp" v-if="recodeList.length!=0">
                <ul class="recordW">
                    <li v-for="(item,index) in recodeList" :key="index">
                        <div class="reName flex">
                            <span>产品名称：{{item.cardNum==0?item.cardBank+'元话费直充':item.cardBank+'元话费充值卡'}}</span>
                            <div>
                                <span v-if="item.status==0">兑换中</span>
                                <span v-if="item.status==1">兑换成功</span>
                                <span v-if="item.status==2">兑换失败</span>
                                <span v-if="item.status==4">已兑换</span>
                                <span v-if="item.status==5">已过期</span>
                                <span v-if="item.status==6">已废弃</span>
                                <span v-if="item.status==7">已转卖</span>
                            </div>

                        </div>
                        <div class="reInfoW">
                            <div class="reInfo">
                                <p>时间：{{item.addDate}}</p>
                                <p v-if="typeFlag==0">充值账号：{{item.cardUser}}</p>
                                <p v-if="typeFlag==1">卡号：{{item.number?item.number:'— —'}}</p>
                                <p v-if="typeFlag==1">卡密：{{item.number?item.password:'— —'}}</p>
                                <p>服务费：{{(Number(item.totalAmount)-Number(item.cardBank)-Number(item.taxFee))|toPrice}}</p>
                                <p>税费：{{item.taxFee|toPrice}}</p>
                                <p class="total">合计：{{item.totalAmount|toPrice}}</p>
                            </div>
                        </div>
                        <a class="pBUse" :href="item.orderNum" v-if="item.cardNum==1 && item.status==1">立即使用</a>
                    </li>
                </ul>
            </cube-scroll>
            <no-data :data="recodeList"></no-data>
        </div>
    </div>
</template>
<script>
import { phoneLogs } from 'api';
import { mapGetters ,mapActions } from 'vuex';
import {vipCustom} from '@/mixins'
export default {
  mixins: [vipCustom],
    data: () => ({
        typeFlag: 0,
        recodeList: [],
        pullUpLoad: true,
        pullUpLoadThreshold: 0,
        pullUpLoadMoreTxt: '上拉加载更多...',
        pullUpLoadNoMoreTxt: '没有更多数据了~~',
        start:0,
        tenFlag: true,
        time: 0,
        code: '',
    }),
    components: {
        NoData: () => import('components/NoData')
    },
    computed: {
        options() {
            return {
                pullUpLoad: this.pullUpLoadObj,
            }
        },
        pullUpLoadObj: function() {
            return this.pullUpLoad ? {
                threshold: parseInt(this.pullUpLoadThreshold),
                txt: {
                    more: this.pullUpLoadMoreTxt,
                    noMore: this.pullUpLoadNoMoreTxt
                }
            } : false
        },
        ...mapGetters({
            getToken: 'getToken',
            userinfo: 'getUserinfo',
            phoneConfig: 'phone/getConfig'
        }),
    },
    methods: {
        initData() {
          this.start=0;
          this.recodeList = [];
          this.tenFlag = true
        },
        directCharge() {
          this.typeFlag = 0;
          this.initData();
          this.getScenicList();
        },
        cardCharge() {
          this.typeFlag = 1;
          this.initData();
          this.getScenicList();
        },
        async getScenicList() {
            let data = await phoneLogs({
              token: this.getToken,
              history_type: this.typeFlag,
              start: this.start,
            });
            if (data.error_code != 0) {
              return this.$toast(data.message);
            }
            for(var i=0;i<data.data.length;i++){
                if(data.data[i].orderNum && data.data[i].orderNum.indexOf('https')!=-1){
                data.data[i]['number'] = this.getUrlParam("number",data.data[i].orderNum);
                data.data[i]['password'] = this.getUrlParam("password",data.data[i].orderNum)
              }
            }
            this.recodeList.push(...data.data);
            if (data.data.length < 10) {
                this.tenFlag = false;
            }
        },
        onPullingUp() {
            if (this.tenFlag === true) {
                this.start+=10
                this.getScenicList();
            }
            if (!this.tenFlag && this.recodeList.length > 0) {
                this.$refs.scroll.forceUpdate();
            }
        },
        getUrlParam(name,locationUrl){
          var arr = locationUrl.toString().split("?")[1].split('&')
          var res = {}
          for (var i = 0; i < arr.length; i++) {
            res[arr[i].split('=')[0]] = arr[i].split('=')[1]
          }
          return res[name]
        },
    },
    mounted() {
      if(this.$route.query.cardId==1 || this.userinfo.vendorId=='yingqiudi'){
        this.typeFlag = 1;
      }
      this.getScenicList();
    }
}
</script>

<style lang="scss" scoped>
.flex {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
.whoSelectW {
    display: flex;
    justify-content: space-around;
    height: 36px;
    align-items: center;
    background: #373C48;
    P {
        width: 90px;
        text-align: center;
        color: #fff;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 100%;
        font-size: 15px;
        span:first-of-type {
            margin-bottom: 5px;
        }
        span:last-of-type {
            width: 100%;
            height: 2px;
            display: block;
        }
    }
    .whoSelectLogo {
        color: #30CE84;
        span:last-of-type {
            background: #30CE84;
        }
    }
    .divide {
        color: #b1b1b1;
        font-size: 18px;
    }
}

.recordW {
    li {
        border: 1px solid #DEDEDE;
        background: #fff;
        border-radius: 5px;
        margin: 20px 15px;
        font-size: 13px;
        box-sizing: border-box;
        .reName {
          background: transparent;
          line-height: 44px;
          font-size: 15px;
          color: rgb(74, 74, 74);
          padding: 0 10px;
        }
        .reInfoW {
            background: #F4F4F4;
            color: rgb(74, 74, 74);
            .reInfo {
              padding: 0 10px 10px 10px;
              position: relative;
                p {
                    font-size: 12px;
                    padding-top: 15px;
                }
                .total{
                  position: absolute;
                  bottom: 15px;
                  right: 10px;
                  font-size: 15px;
                }
            }
            .recover{
              width: 100%;
              background: #30CE84;
              color: #fff;
              text-align: center;
              line-height: 44px;
              border-radius:0px 0px 5px 5px; /*no*/
              font-size: 15px;
              &.recoverNo{
                background: #DEDEDE;
                color: #4A4A4A;
              }
            }
        }
    }
}

.headFixed {
    position: fixed;
    width: 100%;
    z-index: 2;
    background: #373C48;
}

.scroll-list-wrap {
    padding-top: 80px;
    height: calc(100vh - 80px);
    transform: rotate(0deg); // fix 子元素超出边框圆角部分不隐藏的问题
    overflow: hidden
}

header {
    position: relative;
    background: #373C48;
    line-height: 50px;
    text-align: center;
    font-size: 18px;
    color: #fff;
    padding-bottom: 5px;
    .cubeic-back {
        position: absolute;
        top: 0;
        left: 0;
        padding: 0 15px;
    }
}
.oilRecord{
  background: #fff;
}

.gold-bnt-info{
  background: #ddd;
  text-align: left;
  padding: 0 14px;
  color: #000;
  font-size: 12px;
  overflow: hidden;
  transition: 0.2s;
  height: 0;
  position: relative;
  .backMoney{
    position: absolute;
    bottom: 10px;
    right: 12px;
    font-size: 14px;
  }
  p{
    line-height: 28px;
    &:first-of-type{
      margin-top: 8px;
    }
    &:last-child{
      margin-bottom: 8px;
    }
  }

  .total{
      position: absolute;
      bottom: 6px;
      right: 14px;
      font-size: 15px;
  }
}
.gold-bnt{
    background: #373C48;
    border-radius: 0 0 5px 5px;
    font-size: 15px;
    text-align: center;
    padding: 0;
    display: inherit;
    color: #fff;
    line-height: 44px;
    padding-top:5px;
}
.moreIcon{
    display: inline-block;
    transition: 0.1s;
    width: 20px;
    height:20px;
    background-image: url("../../../common/images/more.png");
    transform:rotate(180deg);
    transition: 0.2s;
}
.pBUse {
    background: #30CE84;
    color: #fff;
    text-align: center;
    line-height: 44px;
    border-radius: 0 0 5px 5px;
    font-size: 15px;
    display: inline-block;
    width: 100%;
    height: 100%;
  }
</style>
<style scoped>
@media screen and (min-width: 600px){
  .headFixed{
    max-width: 384px; /*no*/
    left: 50% !important;
    transform: translateX(-50%);
  }
}
</style>
<style lang="scss">
.cube-dialog-main{
  .cube-dialog-alert{
    .cube-dialog-title{
      .title-wrapper{
        .text{
          padding: 15px 0;
        }
      }
    }
    .cube-dialog-content{
      .content-wrapper{
        padding: 0 15px;
        position: relative;
        .sms-code{
          position: absolute;
          right: 17px;
          top: 0;
          background: transparent;
          border: none;
          font-size: 12px;
          color: #30CE84;
          height: 100%;
        }
      }
    }
  }
}
</style>

// src/pages/phone/record/index.jsx
import Taro,{Component} from "@tarojs/taro"
import {View, Image, Text,Input} from "@tarojs/components"
import './index.scss'
import {connect} from "@tarojs/redux"
import { dialog, filter } from '@/util/index'
import {backInfoFun} from "@/pages/phone/store/action"
import {phoneLogs} from '../api'
import PayPassword from "@/components/PayPassword";
import NoData from "@/components/NoData"

@connect(({phone,user}) => ({
  phone,
  info: user.info,
  token: user.token,
}), dispatch => ({

}))


export default class phoneRecord extends Component {
  config ={
    navigationBarTitleText: '话费充值',
    navigationBarBackgroundColor: '#313340',
    navigationBarTextStyle: 'white'
  }

  constructor(){
    super(...arguments)
    this.selectList=[
      {id:0,name:"直充"},
      {id:1,name:"充值卡"}
    ],
    this.state = {
      typeId:0,
      logsList:[],
      start:0,
      allLoadFlag:false
    }
  }

  selectType(id){
    this.setState({typeId:id});
    this.setState({logsList:[],start:0},()=>{
      this.getLogs();
    });
  }

  componentWillMount() { //将要装载
    this.getLogs();
  }



  //话费记录
  getLogs = async() => {
    let res= await phoneLogs({history_type:this.state.typeId,start:this.state.start,token:this.props.token});
    if(res.error_code!=0) return dialog.toast({title: res.message});
    for(var i=0;i<res.data.length;i++){
      if(res.data[i].orderNum && res.data[i].orderNum.indexOf('https')!=-1){
        res.data[i]['number'] = this.getUrlParam("number",res.data[i].orderNum);
        res.data[i]['password'] = this.getUrlParam("password",res.data[i].orderNum)
      }
    }
    this.setState({logsList:this.state.logsList.concat(res.data)});
    if(res.data.length<10){
      this.setState({allLoadFlag:true})
    }
  }

  //截取
  getUrlParam(name,locationUrl){
    var arr = locationUrl.toString().split("?")[1].split('&')
    var res = {}
    for (var i = 0; i < arr.length; i++) {
      res[arr[i].split('=')[0]] = arr[i].split('=')[1]
    }
    return res[name]
  }

  onReachBottom(){
    if(this.state.allLoadFlag==false){
      this.setState(prevState=>{start:prevState.start+=10},()=>{
        this.getLogs();
      })
    }else{
      dialog.toast({title: '没有更多了'})
    }
  }

  statusInfo(status){
    switch (status){
      case 0:
        return "兑换中";
        break;
      case 1:
        return "兑换成功";
        break;
      case 2:
        return "兑换失败";
        break;
      case 4:
        return "已兑换";
        break;
      case 5:
        return "已过期";
        break;
      case 6:
        return "已废弃";
        break;
      case 7:
        return "已转卖";
        break;
    }
  }


  render(){
    return(
      <View className="phoneRecord">
        <View className="headFixed">
            <View className="selectWrap">
              {
                this.selectList.map((item,index)=>{
                  return (
                    <View
                      className={this.state.typeId==index?'selectOne selectActive':'selectOne'}
                      onClick={() => this.selectType(index)}
                      key={index}
                    >
                      <Text className="selectName" >{item.name}</Text>
                    </View>
                  )
                })
              }
            </View>
        </View>


        <View className="recordW">
            <View className="recordUl">
              {
                this.state.logsList&&this.state.logsList.length?(this.state.logsList.map((item,index)=>{
                  return(
                    <View key={index} className="recordLi">
                      <View className="reName flex">
                        <View>产品名称：{item.cardNum==0?item.cardBank+'元话费直充':item.cardBank+'元话费充值卡'}</View>
                        <View>{this.statusInfo(item.status)}</View>
                      </View>
                      <View className="reInfoW">
                        <View className="reInfo">
                          <View className="infoInner">时间：{item.addDate}</View>
                          { this.state.typeId==0 &&<View className="infoInner">充值账号：{item.cardUser}</View> }
                          { this.state.typeId==1 &&<View className="infoInner">卡号：{item.number?item.number:'— —'}</View> }
                          { this.state.typeId==1 &&<View className="infoInner">卡密：{item.number?item.password:'— —'}</View>}
                          <View className="infoInner">服务费：{filter.toDecimal2((item.totalAmount-item.cardBank-item.taxFee))}</View>
                          <View className="infoInner">税费：{filter.toDecimal2(item.taxFee)}</View>
                          <View className="total">合计：{filter.toDecimal2(item.totalAmount)}</View>
                        </View>

                      </View>
                    </View>
                  )
                })
                ): (<Image src={'https://mall.cocotc.cn/static/images/home/nothing.png'} className="notingImg"></Image>)
              }
            </View>
        </View>
    </View>
    )
  }
}
